### ISSUE TITLE
Seeing Error :  [INFO  wait] Host [bitcoin:18443] not yet available...

### ISSUE THREAD

**Issue by Akirtovskis** [dorucioclea/stacks-dev-env#3]
Hello @dorucioclea 

I was also facing issues with running `stacks-local-dev` setup, so after reading the discussion here : 
https://github.com/blockstack/stacks-local-dev/issues/43 I stumble upon this repo. 

However, when following all the setup except BNS part, this is the error that I see : 
<img width="1192" alt="Screenshot 2021-06-20 at 11 25 09" src="https://user-images.githubusercontent.com/25903618/122668861-7317e480-d1ba-11eb-9fec-fd2e337d9ab0.png">

It seems to stay in that state for around 10-15 min after which I stopped it.  Should I wait longer or there's something obvious that I am missing?

**Comment by dorucioclea** [comment]
Hi @Akirtovskis ,im going to need you to do a couple of things.

Before any of that, make sure you have `BNS_IMPORT_DIR: /bns-data` commented out like this:

![image](https://user-images.githubusercontent.com/39082034/122727275-8b9e0280-d27f-11eb-962d-aa0cd5b00144.png)

If it is not commented out, it will attempt to import the bns data and fail at a later stage because you didn't run the `bns.yaml` compose file to download the bns data in the first place :) 

1. Make sure you are running docker WSL2 - it is very important, different networking behaviours between WSL1 and WSL2

There's an issue linked to WSL1 on `stacks blockchain` - https://github.com/blockstack/stacks-blockchain/issues/2198 - people have some weird issues on WSL1

```
wsl.exe -l -v
```

Should give you <LINUX-DISTRIBUTION> Running 2. If It says Running 1, then you're on WSL1 and you need to upgrade. 

For reference my output looks like this:

![image](https://user-images.githubusercontent.com/39082034/122725912-2695dd00-d27e-11eb-9fa7-f865bea9a48c.png)

Also make sure you're not running an outdate version of docker. 

You can check this with 

```
docker -v
```

For reference, the version I'm using: 

![image](https://user-images.githubusercontent.com/39082034/122726263-84c2c000-d27e-11eb-8ec6-718d9c9a5ecd.png)


2. Confirm that you have not done any modifications to configuration or docker compose file 

2. Make sure you're running a clean stack with :

```
docker-compose down --rmi all --volumes
```

The above command removes the containers, images they are based on and volumes

3. Re-do the setup: 

```
docker-compose pull
```

```
docker-compose build
```


4. Save the logs like this

```
docker-compose up > log.txt
```

5. Upload the logfile here

Thank you 👌

**Comment by dorucioclea** [comment]
Closing this issue as I didn't get any response back. Feel free to open if this still persists
